### ISSUE TITLE
Environment suit is not showing when I start a new mission

### ISSUE THREAD

**Issue by woestman** [CritFailMods/Icarus-Mods#2]
Hi,

First - thanks for the mods - makes the game a lot more fun for a casual player like me.  

I just updated the mods and after starting a new mission, am finding my environment suite ( Larkwell one ) is not showing on my person once the mission starts.  I tried exiting and restarting the mission twice and even took off and back put on the environment suit but no luck.  

I have not tried it without the mod yet - hoping this is a known issue and you already have a workaround in place.

Thanks,
Tom

**Comment by CritFailMods** [comment]
Hello,

If you have the “Bye Suits” mod installed, remove it. That mod should only
be installed if you have a lot of extra envirosuits and want to be able to
remove them from your Space Inventory by allowing you to put them in your
Loadout and destroy them once on the planet.

That is the only thing I can currently think of that would be causing
issues. Let me know what mods you are using if you do not have that one
installed.

Thanks,

CritFail

**Comment by woestman** [comment]
Ack!!!  Somehow I accidentally grabbed that mod when downloading.  Removing it worked fine.  Thanks!
